-- Phase 8: offline POS devices + sync.
--
-- Design decision (accountant's call, confirmed in conversation): each POS
-- device gets its own permanent, non-resetting document series
-- (STORE-DEVICE-INV-000001, STORE-DEVICE-CN-000001, ...) instead of a
-- shared company-wide series. This is what lets a device assign a final,
-- ZATCA-compliant document number while fully offline, with zero round trip
-- to the server: the number is real and permanent the instant it's
-- assigned, so there's never a "temp number becomes the real number" step
-- that could desync from what the customer was handed at sale time. A
-- device's series is a legitimate deviation from the company-wide
-- fn_next_document_number series used everywhere else (0005) — it is never
-- generated by the server, only validated and recorded at sync time.
--
-- Per the 0021 comment on zatca_invoice_category: a standard tax invoice
-- must be cleared before the customer receives it, so it cannot be issued
-- offline. Only 'simplified' invoices may carry issued_by_device_id — see
-- check_sales_invoice_device_consistency below.

CREATE TABLE pos_devices (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id     UUID NOT NULL REFERENCES companies(id),
  store_id       UUID NOT NULL REFERENCES stores(id),
  device_code    TEXT NOT NULL,
  device_name    TEXT NOT NULL,
  series_prefix  TEXT NOT NULL, -- e.g. 'ST01-POS3-'; permanent once used, see immutability trigger below
  status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'retired')),
  registered_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  retired_at     TIMESTAMPTZ,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by     UUID REFERENCES users(id),
  UNIQUE (company_id, device_code),
  UNIQUE (company_id, series_prefix)
);

CREATE INDEX idx_pos_devices_company ON pos_devices(company_id);
CREATE INDEX idx_pos_devices_store ON pos_devices(store_id);

CREATE OR REPLACE FUNCTION check_pos_devices_refs_company()
RETURNS TRIGGER AS $$
DECLARE
  ref_company_id UUID;
BEGIN
  SELECT company_id INTO ref_company_id FROM stores WHERE id = NEW.store_id;
  IF ref_company_id IS DISTINCT FROM NEW.company_id THEN
    RAISE EXCEPTION 'store % does not belong to company %', NEW.store_id, NEW.company_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pos_devices_check_refs
  BEFORE INSERT OR UPDATE ON pos_devices
  FOR EACH ROW EXECUTE FUNCTION check_pos_devices_refs_company();

-- A device's identity (its series prefix above all) is permanent once it
-- has actually issued a document under it — a series, once started, is
-- never restarted or handed to a different physical device. Retiring a
-- device (status -> 'retired') is allowed any time; changing what it *is*
-- is not, once it has history.
CREATE OR REPLACE FUNCTION check_pos_devices_immutable_identity()
RETURNS TRIGGER AS $$
BEGIN
  IF current_setting('app.bypass_immutability', true) = 'true' THEN
    RETURN NEW;
  END IF;

  IF NEW.series_prefix IS DISTINCT FROM OLD.series_prefix
     OR NEW.device_code IS DISTINCT FROM OLD.device_code
     OR NEW.company_id IS DISTINCT FROM OLD.company_id
     OR NEW.store_id IS DISTINCT FROM OLD.store_id THEN
    IF EXISTS (
      SELECT 1 FROM pos_device_sequences
      WHERE device_id = OLD.id AND last_synced_seq > 0
    ) THEN
      RAISE EXCEPTION 'device % has already issued documents under its identity; it cannot be changed', OLD.id;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pos_devices_immutable_identity
  BEFORE UPDATE ON pos_devices
  FOR EACH ROW EXECUTE FUNCTION check_pos_devices_immutable_identity();

CREATE TRIGGER trg_pos_devices_audit
  AFTER INSERT OR UPDATE OR DELETE ON pos_devices
  FOR EACH ROW EXECUTE FUNCTION fn_audit_trigger();

-- One row per (device, document_type): the server's record of the last
-- number it has confirmed synced for that device's series. This is the
-- authority for "what number comes next" at sync-validation time — it is
-- never a generator. The device always generates; the server only checks
-- the device's claimed number is exactly one more than this, then records
-- it. Gaps and duplicates are therefore rejected at sync, not silently
-- absorbed.
CREATE TABLE pos_device_sequences (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  device_id       UUID NOT NULL REFERENCES pos_devices(id),
  document_type   TEXT NOT NULL CHECK (document_type IN ('pos_invoice', 'credit_note')),
  last_synced_seq BIGINT NOT NULL DEFAULT 0 CHECK (last_synced_seq >= 0),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (device_id, document_type)
);

CREATE INDEX idx_pos_device_sequences_device ON pos_device_sequences(device_id);

ALTER TABLE sales_invoices
  ADD COLUMN issued_by_device_id     UUID REFERENCES pos_devices(id),
  ADD COLUMN device_sequence_number  BIGINT,
  ADD COLUMN client_uuid             UUID; -- client-generated idempotency key for sync retries

-- Partial unique indexes: most invoices have no device/client_uuid at all
-- (wholesale, or POS created directly online), so these only constrain the
-- rows that actually went through the offline path.
CREATE UNIQUE INDEX uq_sales_invoices_client_uuid
  ON sales_invoices(company_id, client_uuid) WHERE client_uuid IS NOT NULL;
CREATE UNIQUE INDEX uq_sales_invoices_device_seq
  ON sales_invoices(issued_by_device_id, device_sequence_number) WHERE issued_by_device_id IS NOT NULL;
CREATE INDEX idx_sales_invoices_device ON sales_invoices(issued_by_device_id);

ALTER TABLE credit_notes
  ADD COLUMN issued_by_device_id     UUID REFERENCES pos_devices(id),
  ADD COLUMN device_sequence_number  BIGINT,
  ADD COLUMN client_uuid             UUID;

CREATE UNIQUE INDEX uq_credit_notes_client_uuid
  ON credit_notes(company_id, client_uuid) WHERE client_uuid IS NOT NULL;
CREATE UNIQUE INDEX uq_credit_notes_device_seq
  ON credit_notes(issued_by_device_id, device_sequence_number) WHERE issued_by_device_id IS NOT NULL;
CREATE INDEX idx_credit_notes_device ON credit_notes(issued_by_device_id);

CREATE OR REPLACE FUNCTION check_sales_invoice_device_consistency()
RETURNS TRIGGER AS $$
DECLARE
  v_device RECORD;
BEGIN
  IF NEW.issued_by_device_id IS NOT NULL THEN
    SELECT company_id, store_id INTO v_device FROM pos_devices WHERE id = NEW.issued_by_device_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'pos device % not found', NEW.issued_by_device_id;
    END IF;
    IF v_device.company_id IS DISTINCT FROM NEW.company_id OR v_device.store_id IS DISTINCT FROM NEW.store_id THEN
      RAISE EXCEPTION 'pos device % does not belong to company % / store %', NEW.issued_by_device_id, NEW.company_id, NEW.store_id;
    END IF;
    IF NEW.zatca_invoice_category <> 'simplified' THEN
      RAISE EXCEPTION 'a device-issued invoice must be zatca_invoice_category simplified, not %; standard invoices cannot be issued offline', NEW.zatca_invoice_category;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_sales_invoices_device_consistency
  BEFORE INSERT OR UPDATE ON sales_invoices
  FOR EACH ROW EXECUTE FUNCTION check_sales_invoice_device_consistency();

CREATE OR REPLACE FUNCTION check_credit_note_device_consistency()
RETURNS TRIGGER AS $$
DECLARE
  v_device RECORD;
BEGIN
  IF NEW.issued_by_device_id IS NOT NULL THEN
    SELECT company_id, store_id INTO v_device FROM pos_devices WHERE id = NEW.issued_by_device_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'pos device % not found', NEW.issued_by_device_id;
    END IF;
    IF v_device.company_id IS DISTINCT FROM NEW.company_id OR v_device.store_id IS DISTINCT FROM NEW.store_id THEN
      RAISE EXCEPTION 'pos device % does not belong to company % / store %', NEW.issued_by_device_id, NEW.company_id, NEW.store_id;
    END IF;
    IF NEW.zatca_invoice_category <> 'simplified' THEN
      RAISE EXCEPTION 'a device-issued credit note must be zatca_invoice_category simplified, not %', NEW.zatca_invoice_category;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_credit_notes_device_consistency
  BEFORE INSERT OR UPDATE ON credit_notes
  FOR EACH ROW EXECUTE FUNCTION check_credit_note_device_consistency();

-- New permission for the one genuinely new capability this phase adds
-- (registering/retiring devices). Pushing offline documents reuses the
-- existing sales.pos_invoice.create / sales.return.create codes from 0010 —
-- syncing an offline sale is still "creating a sales invoice", just via a
-- different route.
INSERT INTO permissions (module, action, code, description) VALUES
  ('sales', 'manage_pos_device', 'sales.pos_device.manage', 'Register and retire offline POS devices');
